# Generated by Django 3.2.3 on 2021-06-17 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_gallery_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='item',
        ),
        migrations.AddField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='core.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_long',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='description_short',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('S', 'sale'), ('N', 'new'), ('P', 'promotion')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
