# Generated by Django 3.2.3 on 2021-06-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210617_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemStock',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_gallery', to='core.product'),
        ),
    ]
